apiVersion: v1
kind: PersistentVolume
metadata:
  name: xpayadlsgen2-xpayweb3-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: xpayadlsgen2-xpayweb3
    volumeAttributes:
      containerName: xpayweb3
    nodeStageSecretRef:
      name: xpayadlsgen2-secret
      namespace: default
    # kubectl create secret generic xpayadlsgen2-secret --from-literal azurestorageaccountname={ACCOUNT_NAME} --from-literal azurestorageaccountkey={ACCOUNT_KEY} --type=Opaque --namespace=default