apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xpayadlsgen2-xpayweb3-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: xpayadlsgen2-xpayweb3-pv
  storageClassName: azureblob-fuse-premium